export let dictionary = [
    "function definition",
    "type inference",
    "boolean operators",
    "and",
    "or",
    "not",
    "reassignment operators",
    "unreachable code",
    "preventing infinite loops",
    "0-based indexing",
    "arrays",
    "array length",
    "swap two variables",
    "copy an array",
    "filter an array",
    "return type",
    "return",
    "parameters",
    "function signature",
    "return value",
    "arguments",
    "expression",
    "class",
    "object",
    "property",
    "function call",
    "union type",
    "optional parameter",
    "default value",
    "undefined",
    "assignment",
    "increment",
    "decrement",
    "local variables",
    "scope",
    "statements",
    "if-else",
    "else-if",
    "boolean expression",
    "looping",
    "while loop",
    "for loop",
    "algorithm",
    "linear search",
    "array index",
    "find minimum",
    "find maximum",
    "sum values",
    "primitive type",
    "composite type",
    "number",
    "boolean",
    "row major",
    "column major",
    "string",
    "main function",
    "constructor",
    "2d-array"
];